#include<stdio.h>
#include<conio.h>
void main()
{
clrscr();
printf("Hello Programming\n");
getch();
}
/*
Execution Steps of a C Program:

			Source Code[exect.cpp]
			       |
			       |
			       |Compile
			       |-Error Detection
			       |-Convert HLL------>LLL
			       |
			       |
			Object Code[exect.obj]
			       |
			       |Linker & Loader
			       |
			       |
			       |
		       Executable Code[exect.exe]
*/