#include<stdio.h>
#include"conio.h"
void main()
{
clrscr();//clrscr is a functionwhich clears up the last outputted screen.
printf("Hello Programming");
getch();
}

/*

f(x,y)=2x+3y   f(2,3)=13

Satisf/Disatis CallMom()
{

}


Function:
1. Function Declaration or Function Prototype
Mr Abc();
Miss Pqr();

2. Function Definition
Mr Abc()
{
C, C++, Java, 2+years;
}

Miss Pqr()
{
C, C++, .NET,3+years;
}

3. Function Calling
Abc();
Pqr();


# is a pre-processor directive
include is a directory or folder
< > " "     Delimiters or Separators
( )  parenthesis
{ }  opening & closing curly braces or blocks
main()
printf()
clrscr()
getch()
-These four are functions
-stdio stands for standard input output
-conio stands for console input output
Every statement inside main() ends with a semi-colon.
*/