#include<stdio.h>
#include<conio.h>
void min()
{
int array[100][100];
int i,j,r,c,max,min,size;
clrscr();
printf("Enter the Size of rows columns:\n");
scanf("%d%d",&r,&c);
    printf("Enter the %d elements in the array:\n",r*c);
   for(i=0;i<r;i++)
  {
    for(j=0;j<c;j++)
     scanf("%d",array[i]);
  }
  for(i=0;i<r;i++)
  {
    for(j=0;j<c;j++)
     printf("%d\t",array[j]);
  }

     printf("Entered Matrix is:\n");
  max=array[0];
  min=array[0];
    for(
     if(arr[i]>max
    {
      max arr[i];
    }
       printf("max element =%d\n",n);
       printf("min element =%d",min);
      return 0;

    }

