#include<stdio.h>
#include<conio.h>
void main()
{
int a,b;
clrscr();
printf("enter value of a and b:\n");
scanf("%d%d",&a,&b);
printf("value of a and b b4 swapping is %d and %d\n",a,b);
//a=a+b;this was by + and -.
//b=a-b;
//a=a-b;

//a=a*b;this was by * and /.
//b=a/b;
//a=a/b;

//a=a^b;this was using EXOR.
//b=a^b;
//a=a^b;


printf("value of a and b after swapping is %d and %d\n",a,b);
getch();
}
